//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.BookCopies = new HashSet<BookCopies>();
        }
    
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Annotation { get; set; }
        public Nullable<int> Available { get; set; }
    
        public virtual ICollection<BookCopies> BookCopies { get; set; }
    }
}
