//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopies
    {
        public BookCopies()
        {
            this.Loans = new HashSet<Loans>();
        }
    
        public int CopyId { get; set; }
        public int BookId { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ICollection<Loans> Loans { get; set; }
    }
}
