//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        public int LoanId { get; set; }
        public int CopyId { get; set; }
        public int ReaderId { get; set; }
        public System.DateTime LoanDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<bool> IsReturned { get; set; }
    
        public virtual BookCopies BookCopies { get; set; }
        public virtual Readers Readers { get; set; }
    }
}
